name: Feature Request - iso-builder
description: Suggest a new feature for the iso-builder submodule
title: "[Feature] iso-builder: "
labels: ["enhancement", "iso-builder"]
assignees:
  - macjunkins

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request for iso-builder

        Thank you for suggesting a new feature for the iso-builder submodule of AcreetionOS ARM64.

        Please provide detailed information about the proposed feature.

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Build Process Enhancement
        - New Hardware Platform Support
        - Package Management Improvement
        - Bootloader Configuration
        - Performance Optimization
        - Cross-compilation Enhancement
        - Configuration Management
        - Testing and Validation
      default: 0
    validations:
      required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the proposed feature
      placeholder: Describe the feature you would like to see
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the problem or limitation this feature addresses:
        - Current build system limitations...
        - Hardware support gaps...
        - Performance bottlenecks...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed implementation
      placeholder: |
        How would you like this feature to work?
        - Build process changes...
        - Configuration modifications...
        - New hardware support...

  - type: dropdown
    id: arm64-compatibility
    attributes:
      label: ARM64 Compatibility
      description: How does this feature relate to ARM64 support?
      options:
        - ARM64-specific feature
        - Enhances ARM64 compatibility
        - Cross-architecture feature
        - No ARM64-specific considerations
    validations:
      required: true

  - type: dropdown
    id: milestone-alignment
    attributes:
      label: Milestone Alignment
      description: Which project milestone does this feature support?
      options:
        - Milestone 0 - Infrastructure Setup
        - Milestone 1 - ARM64 Conversion & First ISO
        - Milestone 2 - Bootable System & Hardware Support
        - Milestone 3 - AcreetionOS Identity & Branding
        - Milestone 4 - Production Release Preparation
        - Future Enhancement (post-v1.0)
    validations:
      required: true

  - type: checkboxes
    id: cross-repository-impact
    attributes:
      label: Cross-Repository Impact
      description: How might this feature affect other submodules?
      options:
        - label: This feature requires changes in other submodules
        - label: This feature provides new integration points
        - label: This feature affects the build system
        - label: This feature requires documentation updates
        - label: This feature affects testing infrastructure

  - type: textarea
    id: upstream-considerations
    attributes:
      label: Upstream Considerations
      description: |
        How does this feature relate to upstream projects?
        Consider impact on archiso compatibility, AcreetionOS integration
      placeholder: |
        Consider impact on:
        - archiso framework compatibility
        - AcreetionOS upstream integration
        - Package repository requirements

  - type: dropdown
    id: implementation-complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature is to implement?
      options:
        - Low - Simple changes, minimal impact
        - Medium - Moderate complexity, some integration required
        - High - Complex implementation, significant changes
        - Very High - Major architectural changes required
    validations:
      required: true

  - type: textarea
    id: testing-strategy
    attributes:
      label: Testing Strategy
      description: How should this feature be tested?
      placeholder: |
        Describe testing approach:
        - Build process testing...
        - Hardware compatibility testing...
        - Performance impact assessment...
        - Cross-compilation validation...

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: Describe any alternative approaches you've thought about

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the feature request:
        - Related hardware platforms
        - Performance requirements
        - Integration requirements
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: validation
    attributes:
      label: Validation Checklist
      description: Please confirm you have done the following
      options:
        - label: I have searched existing issues and PRs for similar features
          required: true
        - label: I have considered the ARM64 compatibility implications
          required: true
        - label: I have aligned this feature with project milestones
          required: true
        - label: I have considered upstream compatibility requirements
          required: true